repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.0
  hooks:
    - id: go-fmt
    - id: go-vet
    - id: go-imports
    - id: validate-toml
    - id: no-go-testing
    - id: golangci-lint
      args: [--timeout=2m0s]
    - id: go-critic
    - id: go-unit-tests
    - id: go-build
